### ISSUE TITLE
Cancelled transactions show on the UI however the transactions have been submitted and paid

### ISSUE THREAD

**Issue by victaphu** [harmony-one/multisig-react#17]
We used the multi-sig to send ONE to multiple user addresses; however even though the transactions were successful the UI shows cancelled for all successful transactions. See screenshot below:

![image](https://user-images.githubusercontent.com/44614771/153689103-f487769d-56dd-4a62-9a0b-409c41ed9bc8.png)

Multisig is here:
https://multisig.harmony.one/#/safes/0xd65CEfD16519DdFAdef0F7CBb59F6C18A3920EcB/transactions

**Comment by avitretiak** [comment]
Can confirm I've observed this happen on multiple multi-sigs too, transactions get unanimous confirmations and still show as cancelled even though they went through.

**Comment by victaphu** [comment]
This happens because the indexer is out of sync.
Addressing this issue has fixed the general vault issues we see above. Closing.
